### ISSUE TITLE
skips imports of modules that export a unicode character

### ISSUE THREAD

**Issue by elaforge** [yav/graphmod#23]
E.g.:

    % cat T.hs
    module T (ø) where
    import H
    % cat H.hs
    module H where
    % graphmod T.hs
    ... (only T, no H)
    
But if I remove the ø export, I see T and H.

Also, this is maybe unrelated, but when I remove ø and get the expected output, I still get an unexpected warning:

    WARNING: Multiple files for module H (picking the first):
    ./H.hs,./H.hs

**Comment by yav** [comment]
OK, I think the main thing should be fixed now---the issue was in the lexer package, so all you need to do is  depend haskell-lexler 1.0.2 instead.

I couldn't reproduce the warning, but I modified the code to ignore file names that are exactly the same
as this is the right behavior anyway.

Would you mind giving it a try, and if it seems to work OK for you, I'll upload it to hackage.

**Comment by elaforge** [comment]
Yes, I'm now seeing the proper graph edges, and the multiple files warning is gone now too.

Thanks for the quick fix!
