### ISSUE TITLE
Odd behavior for collapsing

### ISSUE THREAD

**Issue by pacak** [yav/graphmod#25]
Given following modules

```
module C where

module A.A1 where
import B

module A.A2 where
import C

module B where

module A where
import A.A1
import A.A2

module D
import A
```

we get a nice looking structure:
![1](https://user-images.githubusercontent.com/66211/54728357-61e56500-4bb8-11e9-9c9c-6ba54916caea.png)

When running with `-C A` this produces following - modules B and C seems unconnected.

![2](https://user-images.githubusercontent.com/66211/54728358-627dfb80-4bb8-11e9-8ed5-0293dec0f1dc.png)

But what I'd like to see is something like this instead.

![3](https://user-images.githubusercontent.com/66211/54728359-627dfb80-4bb8-11e9-9d43-fbb5a81d63a5.png)

**Comment by yav** [comment]
Hi, I think I've fixed this.  Would you mind trying it out (from the github repo) on your example, and let me know if it seems to work as expected.

**Comment by pacak** [comment]
![1](https://user-images.githubusercontent.com/66211/55041590-ac5b5b80-5068-11e9-89be-d3195eaee67d.png)

Much better. Does it makes sense to add some decoration that A is collapsed node? Like make it a double circle or something? Or a box?

**Comment by yav** [comment]
Collapsed nodes are colored using the background color of the cluster that got collapsed---notice that `A` is gray.   The shape of the collapsed node is round If there is a module with the same name as the cluster (e.g., in this example there is both a module `A` and a directory `A`).   If you drew the graph so that only the directory is collapsed, but not the module, then the collapsed node should look like a rectangle (e.g., try it with `--no-module-in-cluster --collapse=A`).

I am open to changing the styles if you have suggestions for improvements.

**Comment by pacak** [comment]
I see. In this case it's good enough, I'll make a new issue if I come up with a better way of representing it.
