### ISSUE TITLE
Spurious dep with --collapse-module

### ISSUE THREAD

**Issue by chreekat** [yav/graphmod#6]
[Snowdrift](https://github.com/snowdriftcoop/snowdrift/) has a couple local "Data.*" modules. If I use `--collapse-module Data`, src/Application.hs is shown to have a dependency on the "Data" cluster even though it doesn't depend on any of these local modules. Maybe it's because src/Application.hs depends on the (external) module Data.Function?

Suggested invocation for the Snowdrift codebase:

    graphmod -q \
        -C Data -C Handler -C Settings \
        -c View -c Widgets -c Model -c Import \
        -i src src/Application.hs \
        > mods-simple.gv

**Comment by chreekat** [comment]
Oh! It happens not just for --collapse-module but for --collapse as well. My mistake. I'm trying to patch things myself but was on the wrong track.

**Comment by yav** [comment]
Hi, thanks for reporting this!  It's been a while since I've looked at the collapsing code, so I don't really know what's happening here.  If you figure out what's wrong I'd be happy to merge in the change.  If you get stuck please ping me again, and I'll have a look and page it all back it.

By the way, did you see the `-p` flag to graphmod?  I find it quite handy for looking at projects with lots of modules (and I just fixed a bug in its implementation, so hopefully now it will be more reasonable).

**Comment by chreekat** [comment]
I'm giving up for now, so if you want to take a crack at it do feel free.

I am familiar with the -p option, but since my current goal is to minimize
the *actual *connections between components, the long list of -c options is
giving me a much better overview. `graphmod` is the only way I could
possibly be accomplishing this goal, by the way. :) Thanks for the tool!

Out of curiosity, what did you fix? -p seems to have the same behavior for
me, with and without --no-cluster.

On Thu, Nov 12, 2015 at 5:15 PM, Iavor S. Diatchki <notifications@github.com

**Comment by chreekat** [comment]
Actually, give me another day to come up with a patch. I didn't "give up" so much as "not even try", and I would actually enjoy the practice of understanding someone else's code. I'll see if I can't figure it out.
